# Generated by Django 3.0.1 on 2020-10-01 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(8)]),
        ),
    ]
